spring:
  application:
    name: limits-service
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    config:
#      uri: http://localhost:8888
#      profile: dev => It will config get profile limits-service-dev.yml
#      profiles:
#         active: dev


server:
  port: 8081

